<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="14.0.0" />
      <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.1" />
      <PackageReference Include="FluentValidation" Version="12.1.1" />
      <PackageReference Include="MediatR" Version="14.0.0" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.2" />
      <PackageReference Include="Microsoft.Extensions.Azure" Version="1.13.1" />
      <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.2" />
      <PackageReference Include="Microsoft.Identity.Web" Version="4.3.0" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="MediatR" />
        <Using Include="AutoMapper" />
        <Using Include="HikeOrganiser.Core.Model" />
        <Using Include="HikeOrganiser.Core.Interfaces" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\HikeOrganiser.Data\HikeOrganiser.Data.csproj" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
</Project>
