// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace HikeOrganiser.Data.Models
{
    public partial class ContextModel
    {
        private ContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("fc72fe09-3af0-40af-ba2b-b34a11c95f0a"), entityTypeCount: 12)
        {
        }

        partial void Initialize()
        {
            var attendeeInformation = AttendeeInformationEntityType.Create(this);
            var bucketList = BucketListEntityType.Create(this);
            var @event = EventEntityType.Create(this);
            var referralCode = ReferralCodeEntityType.Create(this);
            var user = UserEntityType.Create(this);
            var userReferralCode = UserReferralCodeEntityType.Create(this);
            var identityRole = IdentityRoleEntityType.Create(this);
            var identityRoleClaim = IdentityRoleClaimEntityType.Create(this);
            var identityUserClaim = IdentityUserClaimEntityType.Create(this);
            var identityUserLogin = IdentityUserLoginEntityType.Create(this);
            var identityUserRole = IdentityUserRoleEntityType.Create(this);
            var identityUserToken = IdentityUserTokenEntityType.Create(this);

            AttendeeInformationEntityType.CreateForeignKey1(attendeeInformation, @event);
            AttendeeInformationEntityType.CreateForeignKey2(attendeeInformation, user);
            BucketListEntityType.CreateForeignKey1(bucketList, user);
            EventEntityType.CreateForeignKey1(@event, bucketList);
            EventEntityType.CreateForeignKey2(@event, user);
            UserEntityType.CreateForeignKey1(user, user);
            UserReferralCodeEntityType.CreateForeignKey1(userReferralCode, referralCode);
            UserReferralCodeEntityType.CreateForeignKey2(userReferralCode, user);
            IdentityRoleClaimEntityType.CreateForeignKey1(identityRoleClaim, identityRole);
            IdentityUserClaimEntityType.CreateForeignKey1(identityUserClaim, user);
            IdentityUserLoginEntityType.CreateForeignKey1(identityUserLogin, user);
            IdentityUserRoleEntityType.CreateForeignKey1(identityUserRole, identityRole);
            IdentityUserRoleEntityType.CreateForeignKey2(identityUserRole, user);
            IdentityUserTokenEntityType.CreateForeignKey1(identityUserToken, user);

            AttendeeInformationEntityType.CreateAnnotations(attendeeInformation);
            BucketListEntityType.CreateAnnotations(bucketList);
            EventEntityType.CreateAnnotations(@event);
            ReferralCodeEntityType.CreateAnnotations(referralCode);
            UserEntityType.CreateAnnotations(user);
            UserReferralCodeEntityType.CreateAnnotations(userReferralCode);
            IdentityRoleEntityType.CreateAnnotations(identityRole);
            IdentityRoleClaimEntityType.CreateAnnotations(identityRoleClaim);
            IdentityUserClaimEntityType.CreateAnnotations(identityUserClaim);
            IdentityUserLoginEntityType.CreateAnnotations(identityUserLogin);
            IdentityUserRoleEntityType.CreateAnnotations(identityUserRole);
            IdentityUserTokenEntityType.CreateAnnotations(identityUserToken);

            AddAnnotation("ProductVersion", "9.0.3");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
