// <auto-generated />
using HikeOrganiser.Data.Models;
using HikeOrganiser.Data.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(HikeOrganiserContext), typeof(ContextModel))]
