<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-HikeOrganiser.API-6be1927f-0097-4705-b1b9-b87008934576</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Identity.Web" Version="4.3.0" />
    <PackageReference Include="Microsoft.Identity.Web.DownstreamApi" Version="4.3.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.12.27" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HikeOrganiser.Core\HikeOrganiser.Core.csproj" />
  </ItemGroup>
</Project>
